import Header from '@/components/layout/Header'
import Footer from '@/components/layout/Footer'

export default function TermsOfService() {
  return (
    <main className="min-h-screen bg-white">
      <Header />
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-24">
        <h1 className="text-4xl font-bold text-gray-900 mb-8">Terms of Service</h1>
        <p className="text-sm text-gray-600 mb-8">Last updated: {new Date().toLocaleDateString()}</p>

        <div className="prose prose-lg max-w-none">
          <section className="mb-8">
            <h2 className="text-2xl font-semibold text-gray-900 mb-4">Agreement to Terms</h2>
            <p className="text-gray-700 mb-4">
              By accessing and using Big Motion Studio ("the Service"), you agree to be bound by these Terms of Service. 
              If you do not agree to these terms, please do not use our Service.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold text-gray-900 mb-4">Service Description</h2>
            <p className="text-gray-700 mb-4">
              Big Motion Studio provides automated video generation and social media posting services. Our platform 
              uses AI to create short-form videos and automatically post them to your connected social media accounts 
              (YouTube, TikTok, Instagram).
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold text-gray-900 mb-4">Account Registration</h2>
            <p className="text-gray-700 mb-4">To use our Service, you must:</p>
            <ul className="list-disc pl-6 text-gray-700 space-y-2 mb-4">
              <li>Be at least 18 years old or have parental consent</li>
              <li>Provide accurate and complete registration information</li>
              <li>Maintain the security of your account credentials</li>
              <li>Be responsible for all activities under your account</li>
              <li>Notify us immediately of any unauthorized access</li>
            </ul>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold text-gray-900 mb-4">Platform Authorization</h2>
            <p className="text-gray-700 mb-4">
              By connecting your YouTube, TikTok, or Instagram accounts, you authorize Big Motion Studio to:
            </p>
            <ul className="list-disc pl-6 text-gray-700 space-y-2 mb-4">
              <li>Post videos to your accounts on your behalf</li>
              <li>Access your account information necessary for posting</li>
              <li>Store OAuth tokens securely for automated posting</li>
            </ul>
            <p className="text-gray-700 mb-4">
              You can revoke these permissions at any time through your account settings.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold text-gray-900 mb-4">Content Ownership and Rights</h2>
            <p className="text-gray-700 mb-4">
              <strong>Your Content:</strong> You retain all ownership rights to videos generated through our Service. 
              However, you grant us a license to process, generate, and post content on your behalf.
            </p>
            <p className="text-gray-700 mb-4">
              <strong>AI-Generated Content:</strong> Content generated by our AI is provided as-is. You are responsible 
              for reviewing and ensuring compliance with platform policies before posting.
            </p>
            <p className="text-gray-700 mb-4">
              <strong>Third-Party Content:</strong> Stock footage and music used in videos are licensed from third-party 
              providers (Pexels, Pixabay). You must comply with their licensing terms.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold text-gray-900 mb-4">Prohibited Uses</h2>
            <p className="text-gray-700 mb-4">You agree not to use the Service to:</p>
            <ul className="list-disc pl-6 text-gray-700 space-y-2 mb-4">
              <li>Create content that violates any laws or regulations</li>
              <li>Generate hateful, violent, or illegal content</li>
              <li>Impersonate others or misrepresent yourself</li>
              <li>Spam or engage in deceptive practices</li>
              <li>Violate platform policies of YouTube, TikTok, or Instagram</li>
              <li>Reverse engineer or attempt to access our source code</li>
              <li>Use the Service for any commercial resale purposes</li>
            </ul>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold text-gray-900 mb-4">Subscription and Billing</h2>
            <p className="text-gray-700 mb-4">
              <strong>Payment:</strong> Subscription fees are billed in advance on a monthly or annual basis. All fees 
              are non-refundable except as required by law.
            </p>
            <p className="text-gray-700 mb-4">
              <strong>Cancellation:</strong> You may cancel your subscription at any time. Your access will continue 
              until the end of your current billing period.
            </p>
            <p className="text-gray-700 mb-4">
              <strong>Price Changes:</strong> We reserve the right to modify pricing with 30 days notice to existing subscribers.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold text-gray-900 mb-4">Service Limitations</h2>
            <p className="text-gray-700 mb-4">
              We strive to provide reliable service, but we do not guarantee uninterrupted access. The Service is 
              provided "as is" and "as available." We reserve the right to:
            </p>
            <ul className="list-disc pl-6 text-gray-700 space-y-2 mb-4">
              <li>Modify or discontinue features with notice</li>
              <li>Perform maintenance that may temporarily affect availability</li>
              <li>Set usage limits (video generation quotas, API rate limits)</li>
            </ul>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold text-gray-900 mb-4">Limitation of Liability</h2>
            <p className="text-gray-700 mb-4">
              To the maximum extent permitted by law, Big Motion Studio shall not be liable for any indirect, incidental, 
              special, or consequential damages arising from your use of the Service. This includes, but is not limited to, 
              damages for loss of profits, data, or other intangible losses.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold text-gray-900 mb-4">Termination</h2>
            <p className="text-gray-700 mb-4">
              We reserve the right to suspend or terminate your account if you violate these Terms of Service or engage 
              in activities that harm our Service or other users. Upon termination, your right to use the Service will 
              immediately cease.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold text-gray-900 mb-4">Changes to Terms</h2>
            <p className="text-gray-700 mb-4">
              We may update these Terms of Service from time to time. We will notify you of significant changes via 
              email or through the Service. Your continued use after changes constitutes acceptance of the new terms.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold text-gray-900 mb-4">Contact Us</h2>
            <p className="text-gray-700 mb-4">
              If you have any questions about these Terms of Service, please contact us at:
            </p>
            <p className="text-gray-700">
              <strong>Email:</strong> <a href="mailto:support@bigmotionstudio.com" className="text-emerald-600 hover:text-emerald-700">support@bigmotionstudio.com</a>
            </p>
          </section>
        </div>
      </div>
      <Footer />
    </main>
  )
}
